const baseBridgeData = {
  bridgeUrl: 'http://127.0.0.1:8765/run',
  assignVariable: true,
  variableName: '',
  saveData: false,
  dataColumn: '',
  returnPath: 'result',
  timeout: 30000,
};

export default function () {
  return {
    'python-bridge': {
      name: 'Python Bridge',
      description: 'Call the local Visual Coding Python bridge action',
      icon: 'riCommandLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditPythonBridge',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'action', 'payload', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        action: 'echo',
        payload: '{\n  "message": "from Automa"\n}',
        ...baseBridgeData,
      },
    },
    'parallel-runner': {
      name: 'Parallel Runner',
      description: 'Run bridge actions with Python threads or processes',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditParallelRunner',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'tasksJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'thread',
        workers: 4,
        repeats: 1,
        tasksJson:
          '[\n  {"action":"uppercase","payload":{"text":"one"}},\n  {"action":"uppercase","payload":{"text":"two"}}\n]',
        ...baseBridgeData,
        returnPath: 'summary',
      },
    },
    'build-app': {
      name: 'Build App',
      description: 'Generate a simple standalone Python app from bridge actions',
      icon: 'riFolderZipLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBuildApp',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'appName', 'actionsJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        appName: 'visual-coding-demo',
        actionsJson:
          '[\n  {"action":"echo","payload":{"message":"built app"}},\n  {"action":"uppercase","payload":{"text":"demo"}}\n]',
        ...baseBridgeData,
        returnPath: 'result.dir',
      },
    },
    'browser-scanner': {
      name: 'Browser Scanner',
      description: 'Scan a page, query CSS/XPath selectors, or suggest selectors with Playwright',
      icon: 'riFocus3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBrowserScanner',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'url', 'html', 'selector', 'hint', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'scan',
        source: 'html',
        url: 'https://example.com',
        html: '<main><h1>Visual Coding</h1><button id="run">Run</button></main>',
        selector: 'button#run',
        hint: 'run',
        maxElements: 80,
        captureNetwork: false,
        ...baseBridgeData,
        returnPath: 'result.snapshot',
        variableName: 'browser_snapshot',
      },
    },
    'resource-store': {
      name: 'Resource Store',
      description: 'Read and write typed local Visual Coding resources',
      icon: 'riDatabase2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditResourceStore',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'resourceName', 'resourceValue', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        resourceName: 'api_url',
        resourceType: 'string',
        resourceDescription: '',
        resourceValue: '"https://example.com"',
        ...baseBridgeData,
        returnPath: 'result.value',
        variableName: 'resource_value',
      },
    },
    'http-client': {
      name: 'HTTP Client',
      description: 'Run an HTTP request through the Visual Coding bridge',
      icon: 'riEarthLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditHttpClient',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'url', 'headersJson', 'body', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        method: 'GET',
        url: 'https://example.com',
        headersJson: '{}',
        bodyMode: 'none',
        body: '',
        jsonBody: '{}',
        timeout: 20,
        maxChars: 200000,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'http_response',
      },
    },
  };
}
