const baseBridgeData = {
  bridgeUrl: 'http://127.0.0.1:8765/run',
  assignVariable: true,
  variableName: '',
  saveData: false,
  dataColumn: '',
  returnPath: 'result',
  timeout: 30000,
};

const androidRefDataKeys = [
  'bridgeUrl',
  'adbPath',
  'deviceId',
  'host',
  'selectorJson',
  'xpath',
  'text',
  'packageName',
  'proxy',
  'remotePath',
  'variableName',
];

const androidQuickBaseData = {
  disableBlock: false,
  description: '',
  adbPath: 'adb',
  deviceId: '',
  connection: 'auto',
  host: '',
  wifi: false,
  packageName: '',
  activity: '',
  apkPath: '',
  selectorJson: '{\n  "text": "Login",\n  "clickable": true\n}',
  xpath: ".//node[@clickable='true']",
  text: 'Hello [[user_name]]',
  key: 'BACK',
  shellCommand: 'getprop ro.build.version.release',
  intentAction: 'android.intent.action.VIEW',
  dataUri: 'https://example.com',
  component: '',
  extrasJson: '{\n  "source": "silverback"\n}',
  proxyOperation: 'set',
  proxy: '127.0.0.1:8080',
  latitude: 52.3676,
  longitude: 4.9041,
  permissionOperation: 'list',
  permission: 'android.permission.POST_NOTIFICATIONS',
  fileOperation: 'list',
  remotePath: '/sdcard/Download',
  localPath: '',
  templatePath: '',
  threshold: 0.86,
  color: '#FFFFFF',
  profileOperation: 'build',
  profileName: 'silverback-android-profile',
  brand: 'Google',
  manufacturer: 'Google',
  model: 'Pixel 7',
  imei: '',
  phoneNumber: '',
  wifiSsid: '',
  events: 100,
  x: 300,
  y: 600,
  x1: 300,
  y1: 900,
  x2: 300,
  y2: 300,
  durationMs: 450,
  seconds: 1,
  clear: false,
  tapBefore: true,
  includeXml: false,
  maxElements: 200,
  appOperation: 'current',
  scriptName: 'silverback-android-script',
  stepsJson:
    '[\n  {"action":"tap","x":300,"y":600},\n  {"action":"text","text":"Hello from Silverback"},\n  {"action":"press","key":"BACK"}\n]',
  devicesJson: '[]',
  tasksJson: '[\n  {"action":"android_state","payload":{"maxElements":20}}\n]',
  workers: 4,
  dryRun: false,
  executionTimeout: 30,
};

function androidActionBlock(name, mode, variableName, extraData = {}) {
  return {
    name,
    description: `Android / ZennoDroid block: ${name}`,
    icon: 'riAndroidLine',
    component: 'BlockBasicWithFallback',
    editComponent: 'EditAndroidAutomation',
    category: 'android',
    inputs: 1,
    outputs: 2,
    allowedInputs: true,
    maxConnection: 1,
    refDataKeys: androidRefDataKeys,
    autocomplete: ['variableName', 'deviceId', 'packageName', 'profileName'],
    data: {
      ...androidQuickBaseData,
      ...baseBridgeData,
      mode,
      returnPath: 'result',
      variableName,
      ...extraData,
    },
  };
}

export default function () {
  return {
    'python-bridge': {
      name: 'Python Bridge',
      description: 'Call the local Silverback Coding Python bridge action',
      icon: 'riCommandLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditPythonBridge',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'action', 'payload', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        action: 'echo',
        payload: '{\n  "message": "from Automa"\n}',
        ...baseBridgeData,
      },
    },
    'parallel-runner': {
      name: 'Parallel Runner',
      description: 'Run bridge actions with Python threads or processes',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditParallelRunner',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'tasksJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'thread',
        workers: 4,
        repeats: 1,
        tasksJson:
          '[\n  {"action":"uppercase","payload":{"text":"one"}},\n  {"action":"uppercase","payload":{"text":"two"}}\n]',
        ...baseBridgeData,
        returnPath: 'summary',
      },
    },
    'build-app': {
      name: 'Build App',
      description: 'Generate a simple standalone Python app from bridge actions',
      icon: 'riFolderZipLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBuildApp',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'appName', 'actionsJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        appName: 'silverback-coding-demo',
        actionsJson:
          '[\n  {"action":"echo","payload":{"message":"built app"}},\n  {"action":"uppercase","payload":{"text":"demo"}}\n]',
        ...baseBridgeData,
        returnPath: 'result.dir',
      },
    },
    'project-template-builder': {
      name: 'Project Template Builder',
      description: 'Generate project scaffolds such as private-vpn-lab or bot-service from Automa',
      icon: 'riFolderZipLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditProjectTemplateBuilder',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'projectName', 'brandName', 'botUsername', 'supportUsername', 'domain', 'runMode', 'deploymentProfile', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'build',
        template: 'private-vpn-lab',
        projectName: 'private-vpn-lab-generated',
        brandName: 'GOY VPN',
        botUsername: 'goy_vpn_robot',
        supportUsername: '@support',
        domain: 'vpn.example.com',
        subscriptionRoutePrefix: 'sub',
        deviceLimit: 10,
        runMode: 'polling',
        deploymentProfile: 'startup',
        httpPort: 8082,
        genericEventPath: '/events',
        startupEventPath: '/startup',
        includeNginx: true,
        overwrite: true,
        ...baseBridgeData,
        timeout: 120000,
        returnPath: 'result.dir',
        variableName: 'project_dir',
      },
    },
    'browser-scanner': {
      name: 'Browser Scanner',
      description: 'Scan pages, query CSS/XPath selectors, capture network events, and run with locked browser profiles on Chromium, Firefox, WebKit, or Camoufox',
      icon: 'riFocus3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBrowserScanner',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'browserEngine', 'profileName', 'url', 'html', 'selector', 'hint', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'scan',
        browserEngine: 'chromium',
        profileName: '',
        autoCreateProfile: true,
        headless: true,
        source: 'html',
        url: 'https://example.com',
        html: '<main><h1>Silverback Coding</h1><button id="run">Run</button></main>',
        selector: 'button#run',
        hint: 'run',
        maxElements: 80,
        captureNetwork: false,
        ...baseBridgeData,
        returnPath: 'result.snapshot',
        variableName: 'browser_snapshot',
      },
    },
    'resource-store': {
      name: 'Resource Store',
      description: 'Read and write typed local Silverback Coding resources',
      icon: 'riDatabase2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditResourceStore',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'resourceName', 'resourceValue', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        resourceName: 'api_url',
        resourceType: 'string',
        resourceDescription: '',
        resourceValue: '"https://example.com"',
        ...baseBridgeData,
        returnPath: 'result.value',
        variableName: 'resource_value',
      },
    },
    'resource-design-builder': {
      name: 'Resource / Design Builder',
      description: 'Build typed field schemas, reusable parallel plans, generated apps and BAS-like runtime forms from Automa',
      icon: 'riLayout4Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditResourceDesignBuilder',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'schemaName', 'schemaTitle', 'fieldsJson', 'valuesJson', 'appName', 'planName', 'tasksJson', 'command', 'cwd', 'envJson', 'inputJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'schemaBuild',
        schemaName: 'startup-intake-fields',
        schemaTitle: 'Startup Intake Fields',
        fieldsJson:
          '[\n  {"name":"api_url","label":"API URL","type":"url","required":true,"default":"https://example.com/api"},\n  {"name":"token","label":"Token","type":"secret"},\n  {"name":"workers","label":"Workers","type":"number","default":4,"min":1,"max":32},\n  {"name":"mode","label":"Mode","type":"select","default":"startup","options":["startup","production"]}\n]',
        valuesJson: '{\n  "api_url": "https://example.com/api",\n  "workers": 4,\n  "mode": "startup"\n}',
        tokensJson: '{\n  "accent": "#7c3aed",\n  "success": "#059669",\n  "warning": "#f59e0b"\n}',
        appName: 'silverback-designed-app',
        appTitle: 'Silverback Coding Designed App',
        planName: 'silverback-parallel-plan',
        planMode: 'thread',
        workers: 4,
        repeats: 1,
        tasksJson:
          '[\n  {"action":"uppercase","payload":{"text":"one"}},\n  {"action":"json_get","payload":{"data":{"user":{"name":"Automa"}},"path":"user.name"}}\n]',
        projectPath: '',
        runtime: 'system',
        shell: 'powershell',
        cwd: '.',
        command: 'Write-Output "Silverback run [[run_index]] with [[TOKEN]]"',
        code: 'result = {"ok": True, "input": input_data}',
        envJson: '{\n  "TOKEN": "[[token]]"\n}',
        envMappingJson: '{\n  "token": "TOKEN",\n  "api_url": "API_URL"\n}',
        inputJson: '{\n  "mode": "startup"\n}',
        packagesJson: '[]',
        androidDevicesJson: '[\n  "emulator-5554",\n  "emulator-5556",\n  "emulator-5558",\n  "emulator-5560",\n  "emulator-5562"\n]',
        androidTasksJson: '[\n  {"action":"android_state","payload":{"maxElements":20}}\n]',
        dryRun: false,
        overwrite: true,
        verify: true,
        saveResult: true,
        ...baseBridgeData,
        timeout: 120000,
        returnPath: 'result',
        variableName: 'resource_design_result',
      },
    },
    'json-tools': {
      name: 'JSON Tools',
      description: 'Create, read, change, validate and stringify JSON through the Silverback Coding bridge',
      icon: 'riBracketsLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditJsonTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'dataJson', 'path', 'valueJson', 'text', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        shape: 'object',
        dataJson: '{\n  "user": {\n    "name": "Automa"\n  }\n}',
        path: 'user.name',
        valueJson: '"Silverback Coding"',
        text: '{"ok":true}',
        indent: 2,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'json_result',
      },
    },
    'list-tools': {
      name: 'List Tools',
      description: 'Create, read, filter, sort, shuffle and compare lists through the Silverback Coding bridge',
      icon: 'riFileListLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditListTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'itemsJson', 'itemJson', 'text', 'key', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'length',
        itemsJson: '[\n  "alpha",\n  "beta",\n  "alpha"\n]',
        itemJson: '"gamma"',
        index: 0,
        start: 0,
        end: '',
        count: 1,
        separator: ',',
        text: 'alpha,beta,gamma',
        key: '',
        reverse: false,
        listsJson: '[\n  ["alpha"],\n  ["beta", "gamma"]\n]',
        rightJson: '[\n  "beta",\n  "gamma"\n]',
        compareMode: 'equals',
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'list_result',
      },
    },
    'logic-tools': {
      name: 'Logic Tools',
      description: 'Evaluate conditions, boolean groups and choose values for If/While style workflows',
      icon: 'riArrowLeftRightLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditLogicTools',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'leftJson', 'rightJson', 'valuesJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'compare',
        operator: 'contains',
        leftJson: '"silverback coding"',
        rightJson: '"coding"',
        valuesJson: '[\n  true,\n  1,\n  "yes"\n]',
        whenTrueJson: '"yes"',
        whenFalseJson: '"no"',
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'logic_result',
      },
    },
    'variable-store': {
      name: 'Variable Store',
      description: 'Persist typed variables that AI, MCP and Automa blocks can share',
      icon: 'mdiVariable',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditVariableStore',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'variableStoreName', 'valueJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        variableStoreName: 'counter',
        variableType: 'number',
        variableScope: 'project',
        variableDescription: '',
        valueJson: '1',
        delta: 1,
        ...baseBridgeData,
        returnPath: 'result.value',
        variableName: 'stored_variable',
      },
    },
    'automa-core-tools': {
      name: 'Automa Core Tools',
      description: 'Read and write Automa native variables, tables and global data without the Python bridge',
      icon: 'riDatabase2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditAutomaCoreTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['coreName', 'corePath', 'valueJson', 'variableName'],
      autocomplete: ['variableName', 'coreName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'setVariable',
        coreName: 'counter',
        corePath: '',
        valueJson: '1',
        delta: 1,
        defaultJson: 'null',
        ...baseBridgeData,
        bridgeUrl: '',
        returnPath: 'result.value',
        variableName: 'automa_core_result',
      },
    },
    'loop-helper': {
      name: 'Loop Helper',
      description: 'Generate range, repeated, chunked or enumerated lists for Automa Loop Data blocks',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditLoopHelper',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'itemsJson', 'itemJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'range',
        itemsJson: '[\n  "alpha",\n  "beta",\n  "gamma"\n]',
        itemJson: '{\n  "ok": true\n}',
        start: 0,
        end: 5,
        step: 1,
        inclusive: false,
        times: 3,
        size: 2,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'loop_items',
      },
    },
    'bas-for-loop': {
      name: 'BAS For Loop',
      description: 'Generate BAS-style For loop rows with an index variable for visible workflow logic',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBasForLoop',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'indexName', 'variableName'],
      autocomplete: ['indexName', 'variableName'],
      data: {
        disableBlock: false,
        description: '',
        start: 0,
        end: 5,
        step: 1,
        inclusive: false,
        indexName: 'i',
        ...baseBridgeData,
        returnPath: 'result.items',
        variableName: 'for_items',
      },
    },
    'bas-foreach-loop': {
      name: 'BAS For Each',
      description: 'Generate BAS-style Foreach rows from an array with item and index variables',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBasForEachLoop',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'itemsJson', 'indexName', 'itemName', 'variableName'],
      autocomplete: ['indexName', 'itemName', 'variableName'],
      data: {
        disableBlock: false,
        description: '',
        itemsJson: '[\n  "alpha",\n  "beta",\n  "gamma"\n]',
        start: 0,
        indexName: 'index',
        itemName: 'item',
        ...baseBridgeData,
        returnPath: 'result.items',
        variableName: 'foreach_items',
      },
    },
    'file-path-tools': {
      name: 'File / Path Tools',
      description: 'Read, write, list, copy and normalize sandboxed files and paths',
      icon: 'riFolderLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditFilePathTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'path', 'text', 'source', 'target', 'partsJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'write',
        path: 'demo/output.txt',
        text: 'Hello from Silverback Coding',
        source: 'demo/output.txt',
        target: 'demo/copy.txt',
        partsJson: '[\n  "demo",\n  "output.txt"\n]',
        base: '.',
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'file_result',
      },
    },
    'wait-tools': {
      name: 'Wait / Retry Tools',
      description: 'Wait for time, files, HTTP responses, browser selectors and text',
      icon: 'riTimeLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditWaitTools',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'path', 'url', 'selector', 'text', 'actionPayloadJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'sleep',
        seconds: 1,
        path: 'demo/output.txt',
        url: 'https://example.com',
        selector: 'h1',
        text: 'Example',
        browserEngine: 'chromium',
        fileMode: 'exists',
        status: 200,
        state: 'visible',
        headless: true,
        timeoutSeconds: 10,
        interval: 0.5,
        retryAction: 'http_request',
        actionPayloadJson: '{\n  "url": "https://example.com"\n}',
        attempts: 3,
        delaySeconds: 1,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'wait_result',
      },
    },
    'profile-action': {
      name: 'Profile Action',
      description: 'Create, copy, lock, delete and attach metadata/cookies to browser profiles',
      icon: 'riUser3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditProfileAction',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'profileName', 'targetProfileName', 'metadataJson', 'cookiesJson', 'lockToken', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'create',
        profileName: 'demo-browser-profile',
        targetProfileName: 'demo-browser-profile-copy',
        browserEngine: 'chromium',
        profileDescription: '',
        metadataJson: '{\n  "notes": "Silverback Coding profile"\n}',
        cookiesJson: '[]',
        lockToken: '',
        force: false,
        overwrite: false,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'profile_result',
      },
    },
    'network-recorder-import': {
      name: 'Network Recorder Import',
      description: 'Capture browser network events and generate HTTP Client workflow blocks',
      icon: 'riGlobalLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditNetworkRecorderImport',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'url', 'html', 'profileName', 'workflowName', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        source: 'url',
        url: 'https://example.com',
        html: '<main><h1>Network Capture</h1></main>',
        browserEngine: 'chromium',
        profileName: '',
        workflowName: 'captured-http-workflow',
        limit: 12,
        headless: true,
        ...baseBridgeData,
        timeout: 60000,
        returnPath: 'result.workflow.artifact',
        variableName: 'captured_workflow',
      },
    },
    'manual-intervention': {
      name: 'Manual Intervention',
      description: 'Detect captcha/security checks and create a safe operator pause/resume checkpoint',
      icon: 'riShieldCheckLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditManualIntervention',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'title', 'reason', 'instructions', 'url', 'html', 'text', 'interventionId', 'variableName'],
      autocomplete: ['variableName', 'interventionId'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'captchaCheck',
        title: 'Captcha or manual check',
        reason: 'captcha_or_security_check',
        instructions: 'Resolve captcha/login/security step manually, then resume this checkpoint.',
        source: 'html',
        url: 'https://example.com',
        html: '<main><h1>Security check</h1><p>Verify you are human</p></main>',
        text: '',
        browserEngine: 'chromium',
        profileName: '',
        interventionId: '',
        decision: 'resume',
        note: '',
        screenshot: true,
        force: false,
        wait: false,
        timeoutSeconds: 300,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'manual_intervention',
      },
    },
    'user-interaction': {
      name: 'User Interaction',
      description: 'Show message boxes, request operator input, play sound, focus manual browser control or execute JS in the active page',
      icon: 'riUserVoiceLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditUserInteraction',
      category: 'interaction',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'title', 'message', 'defaultValue', 'inputName', 'code', 'variableName'],
      autocomplete: ['variableName', 'inputName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'messageBox',
        title: 'Silverback Coding',
        message: 'Checkpoint for [[user_name]]',
        defaultValue: '',
        inputName: 'user_input',
        inputJson: '{\n  "message": "hello"\n}',
        code: 'result = input.message;',
        instructions: 'Take manual control in the active browser tab, then approve the checkpoint.',
        frequency: 880,
        durationMs: 240,
        volume: 0.18,
        createIntervention: false,
        wait: false,
        timeoutSeconds: 300,
        logToBridge: true,
        ...baseBridgeData,
        returnPath: 'result.value',
        variableName: 'user_input',
      },
    },
    'android-automation': {
      name: 'Android Automation',
      description: 'Build ZennoDroid-like Android workflows: ADB devices, UI tree, XPath, input, app/package/intent, proxy, geo, files, image checks and multi-device workers',
      icon: 'riAndroidLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditAndroidAutomation',
      category: 'android',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'adbPath', 'deviceId', 'host', 'selectorJson', 'xpath', 'text', 'packageName', 'proxy', 'remotePath', 'variableName'],
      autocomplete: ['variableName', 'deviceId', 'packageName', 'profileName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'devices',
        adbPath: 'adb',
        deviceId: '',
        connection: 'auto',
        host: '',
        wifi: false,
        packageName: '',
        activity: '',
        apkPath: '',
        selectorJson: '{\n  "text": "Login",\n  "clickable": true\n}',
        xpath: ".//node[@clickable='true']",
        text: 'Hello [[user_name]]',
        key: 'BACK',
        shellCommand: 'getprop ro.build.version.release',
        intentAction: 'android.intent.action.VIEW',
        dataUri: 'https://example.com',
        component: '',
        extrasJson: '{\n  "source": "silverback"\n}',
        proxyOperation: 'set',
        proxy: '127.0.0.1:8080',
        latitude: 52.3676,
        longitude: 4.9041,
        permissionOperation: 'list',
        permission: 'android.permission.POST_NOTIFICATIONS',
        fileOperation: 'list',
        remotePath: '/sdcard/Download',
        localPath: '',
        templatePath: '',
        threshold: 0.86,
        color: '#FFFFFF',
        profileOperation: 'build',
        profileName: 'silverback-android-profile',
        brand: 'Google',
        manufacturer: 'Google',
        model: 'Pixel 7',
        imei: '',
        phoneNumber: '',
        wifiSsid: '',
        events: 100,
        x: 300,
        y: 600,
        x1: 300,
        y1: 900,
        x2: 300,
        y2: 300,
        durationMs: 450,
        seconds: 1,
        clear: false,
        tapBefore: true,
        includeXml: false,
        maxElements: 200,
        appOperation: 'current',
        scriptName: 'silverback-android-script',
        stepsJson:
          '[\n  {"action":"tap","x":300,"y":600},\n  {"action":"text","text":"Hello from Silverback"},\n  {"action":"press","key":"BACK"}\n]',
        devicesJson: '[]',
        tasksJson: '[\n  {"action":"android_state","payload":{"maxElements":20}}\n]',
        workers: 4,
        dryRun: false,
        executionTimeout: 30,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'android_result',
      },
    },
    'android-devices': androidActionBlock('ADB Devices', 'devices', 'android_devices', {
      returnPath: 'result.devices',
    }),
    'android-connect': androidActionBlock('ADB Connect', 'connect', 'android_device', {
      returnPath: 'result.deviceId',
    }),
    'android-state': androidActionBlock('Android State', 'state', 'android_state'),
    'android-ui-tree': androidActionBlock('UI Tree', 'uiTree', 'android_tree', {
      returnPath: 'result.elements',
    }),
    'android-analyze': androidActionBlock('Analyze UI', 'analyze', 'android_analysis'),
    'android-find-element': androidActionBlock('Find Element', 'findElement', 'android_element', {
      returnPath: 'result.element',
    }),
    'android-wait-element': androidActionBlock('Wait Element', 'waitElement', 'android_wait_element', {
      returnPath: 'result.element',
    }),
    'android-element-at': androidActionBlock('Element At Point', 'elementAt', 'android_point', {
      returnPath: 'result.element',
    }),
    'android-xpath': androidActionBlock('XPath Query', 'xpath', 'android_xpath', {
      returnPath: 'result.elements',
    }),
    'android-tap': androidActionBlock('Tap', 'tap', 'android_tap'),
    'android-long-click': androidActionBlock('Long Click', 'longClick', 'android_long_click', {
      durationMs: 900,
    }),
    'android-input-text': androidActionBlock('Input Text', 'inputText', 'android_input'),
    'android-swipe': androidActionBlock('Swipe', 'swipe', 'android_swipe'),
    'android-drag': androidActionBlock('Drag', 'drag', 'android_drag', {
      durationMs: 700,
    }),
    'android-press': androidActionBlock('Press Key', 'press', 'android_key'),
    'android-wait': androidActionBlock('Wait', 'wait', 'android_wait'),
    'android-shell': androidActionBlock('ADB Shell', 'shell', 'android_shell', {
      returnPath: 'result.stdout',
    }),
    'android-screenshot': androidActionBlock('Screenshot', 'screenshot', 'android_screenshot', {
      returnPath: 'result.path',
    }),
    'android-notifications': androidActionBlock('Notifications', 'notifications', 'android_notifications', {
      returnPath: 'result.text',
    }),
    'android-app': androidActionBlock('App Control', 'app', 'android_app'),
    'android-packages': androidActionBlock('Packages', 'packages', 'android_packages', {
      returnPath: 'result.packages',
    }),
    'android-intent': androidActionBlock('Intent', 'intent', 'android_intent', {
      dryRun: true,
    }),
    'android-proxy': androidActionBlock('Proxy', 'proxy', 'android_proxy', {
      dryRun: true,
    }),
    'android-location': androidActionBlock('Geo Location', 'location', 'android_location', {
      dryRun: true,
    }),
    'android-permissions': androidActionBlock('Permissions', 'permissions', 'android_permissions', {
      dryRun: true,
    }),
    'android-files': androidActionBlock('Device Files', 'files', 'android_files', {
      dryRun: true,
    }),
    'android-screen-record': androidActionBlock('Screen Record', 'screenRecord', 'android_record', {
      dryRun: true,
      returnPath: 'result.localPath',
    }),
    'android-image-find': androidActionBlock('Find Image', 'imageFind', 'android_image', {
      returnPath: 'result.match',
    }),
    'android-pixel': androidActionBlock('Pixel Check', 'pixel', 'android_pixel', {
      returnPath: 'result.hex',
    }),
    'android-device-profile': androidActionBlock('Device Profile', 'deviceProfile', 'android_profile', {
      dryRun: true,
      returnPath: 'result.profile',
    }),
    'android-monkey': androidActionBlock('Monkey Test', 'monkey', 'android_monkey', {
      dryRun: true,
    }),
    'android-parallel-run': androidActionBlock('Multi-device Run', 'parallelRun', 'android_parallel', {
      dryRun: true,
    }),
    'android-airtest-script': androidActionBlock('Airtest Script', 'buildAirtestScript', 'android_script', {
      returnPath: 'result.script',
    }),
    'result-tools': {
      name: 'Result / Log Tools',
      description: 'Create structured logs, message payloads and random values',
      icon: 'riInformationLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditResultTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'message', 'dataJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'log',
        level: 'info',
        message: 'Silverback Coding result',
        dataJson: '{\n  "ok": true\n}',
        min: 0,
        max: 100,
        integer: true,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'result_value',
      },
    },
    'http-client': {
      name: 'HTTP Client',
      description: 'Run an HTTP request through the Silverback Coding bridge',
      icon: 'riEarthLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditHttpClient',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'url', 'headersJson', 'body', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        method: 'GET',
        url: 'https://example.com',
        headersJson: '{}',
        bodyMode: 'none',
        body: '',
        jsonBody: '{}',
        timeout: 20,
        maxChars: 200000,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'http_response',
      },
    },
    'system-command': {
      name: 'System Command',
      description: 'Run cmd, PowerShell or shell commands and capture stdout/stderr',
      icon: 'riTerminalBoxLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditSystemCommand',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'shell', 'command', 'cwd', 'inputText', 'envJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        shell: 'cmd',
        command: 'echo Hello [[user_name]]',
        cwd: '.',
        inputText: '',
        envJson: '{}',
        dryRun: false,
        executionTimeout: 30,
        maxOutputChars: 200000,
        ...baseBridgeData,
        returnPath: 'result.stdout',
        variableName: 'cmd_output',
      },
    },
    'library-runner': {
      name: 'Library Runner',
      description: 'Run Python or Node code with pip/npm libraries through the Silverback Coding bridge',
      icon: 'riCodeSSlashLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditLibraryRunner',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'runtime', 'packagesJson', 'code', 'inputJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        runtime: 'python',
        packagesJson: '[]',
        code: 'result = input_data["x"] * 3',
        inputJson: '{\n  "x": 14\n}',
        executionTimeout: 30,
        installTimeout: 180,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'library_result',
      },
    },
    'telegram-message': {
      name: 'Telegram Message',
      description: 'Send or dry-run a Telegram message with resources and [[VARIABLE]] templates',
      icon: 'riSendPlaneLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditTelegramMessage',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'valueToken', 'tokenResource', 'chatId', 'text', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        valueToken: '',
        tokenResource: 'telegram_bot_token',
        chatId: '',
        text: 'Привет, [[user_name]]. Сделайте вот этот список действий.',
        parseMode: '',
        dryRun: true,
        requestTimeout: 20,
        ...baseBridgeData,
        returnPath: 'result.payload',
        variableName: 'telegram_message',
      },
    },
    'telegram-bot-builder': {
      name: 'Telegram Bot Builder',
      description: 'Generate a Python or Node Telegram bot project from an Automa workflow',
      icon: 'riChat3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditTelegramBotBuilder',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'appName', 'tokenResource', 'startText', 'commandHandlersJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        runtime: 'python',
        appName: 'silverback-telegram-bot',
        tokenResource: 'telegram_bot_token',
        startText: 'Hello from Silverback Coding bot',
        commandHandlersJson: '[\n  {"command":"ping","response":"pong"}\n]',
        executionTimeout: 30,
        ...baseBridgeData,
        returnPath: 'result.dir',
        variableName: 'telegram_bot_dir',
      },
    },
  };
}
