const baseBridgeData = {
  bridgeUrl: 'http://127.0.0.1:8765/run',
  assignVariable: true,
  variableName: '',
  saveData: false,
  dataColumn: '',
  returnPath: 'result',
  timeout: 30000,
};

export default function () {
  return {
    'python-bridge': {
      name: 'Python Bridge',
      description: 'Call the local Visual Coding Python bridge action',
      icon: 'riCommandLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditPythonBridge',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'action', 'payload', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        action: 'echo',
        payload: '{\n  "message": "from Automa"\n}',
        ...baseBridgeData,
      },
    },
    'parallel-runner': {
      name: 'Parallel Runner',
      description: 'Run bridge actions with Python threads or processes',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditParallelRunner',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'tasksJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'thread',
        workers: 4,
        repeats: 1,
        tasksJson:
          '[\n  {"action":"uppercase","payload":{"text":"one"}},\n  {"action":"uppercase","payload":{"text":"two"}}\n]',
        ...baseBridgeData,
        returnPath: 'summary',
      },
    },
    'build-app': {
      name: 'Build App',
      description: 'Generate a simple standalone Python app from bridge actions',
      icon: 'riFolderZipLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBuildApp',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'appName', 'actionsJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        appName: 'visual-coding-demo',
        actionsJson:
          '[\n  {"action":"echo","payload":{"message":"built app"}},\n  {"action":"uppercase","payload":{"text":"demo"}}\n]',
        ...baseBridgeData,
        returnPath: 'result.dir',
      },
    },
    'project-template-builder': {
      name: 'Project Template Builder',
      description: 'Generate benchmark project scaffolds such as private-vpn-lab from Automa',
      icon: 'riFolderZipLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditProjectTemplateBuilder',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'projectName', 'brandName', 'botUsername', 'supportUsername', 'domain', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'build',
        template: 'private-vpn-lab',
        projectName: 'private-vpn-lab-generated',
        brandName: 'GOY VPN',
        botUsername: 'goy_vpn_robot',
        supportUsername: '@support',
        domain: 'vpn.example.com',
        subscriptionRoutePrefix: 'sub',
        deviceLimit: 10,
        overwrite: true,
        ...baseBridgeData,
        timeout: 120000,
        returnPath: 'result.dir',
        variableName: 'project_dir',
      },
    },
    'browser-scanner': {
      name: 'Browser Scanner',
      description: 'Scan pages, query CSS/XPath selectors, capture network events, and run with locked browser profiles on Chromium, Firefox, WebKit, or Camoufox',
      icon: 'riFocus3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditBrowserScanner',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'browserEngine', 'profileName', 'url', 'html', 'selector', 'hint', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'scan',
        browserEngine: 'chromium',
        profileName: '',
        autoCreateProfile: true,
        headless: true,
        source: 'html',
        url: 'https://example.com',
        html: '<main><h1>Visual Coding</h1><button id="run">Run</button></main>',
        selector: 'button#run',
        hint: 'run',
        maxElements: 80,
        captureNetwork: false,
        ...baseBridgeData,
        returnPath: 'result.snapshot',
        variableName: 'browser_snapshot',
      },
    },
    'resource-store': {
      name: 'Resource Store',
      description: 'Read and write typed local Visual Coding resources',
      icon: 'riDatabase2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditResourceStore',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'resourceName', 'resourceValue', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        resourceName: 'api_url',
        resourceType: 'string',
        resourceDescription: '',
        resourceValue: '"https://example.com"',
        ...baseBridgeData,
        returnPath: 'result.value',
        variableName: 'resource_value',
      },
    },
    'json-tools': {
      name: 'JSON Tools',
      description: 'Create, read, change, validate and stringify JSON through the Visual Coding bridge',
      icon: 'riBracketsLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditJsonTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'dataJson', 'path', 'valueJson', 'text', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        shape: 'object',
        dataJson: '{\n  "user": {\n    "name": "Automa"\n  }\n}',
        path: 'user.name',
        valueJson: '"Visual Coding"',
        text: '{"ok":true}',
        indent: 2,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'json_result',
      },
    },
    'list-tools': {
      name: 'List Tools',
      description: 'Create, read, filter, sort, shuffle and compare lists through the Visual Coding bridge',
      icon: 'riFileListLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditListTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'itemsJson', 'itemJson', 'text', 'key', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'length',
        itemsJson: '[\n  "alpha",\n  "beta",\n  "alpha"\n]',
        itemJson: '"gamma"',
        index: 0,
        start: 0,
        end: '',
        count: 1,
        separator: ',',
        text: 'alpha,beta,gamma',
        key: '',
        reverse: false,
        listsJson: '[\n  ["alpha"],\n  ["beta", "gamma"]\n]',
        rightJson: '[\n  "beta",\n  "gamma"\n]',
        compareMode: 'equals',
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'list_result',
      },
    },
    'logic-tools': {
      name: 'Logic Tools',
      description: 'Evaluate conditions, boolean groups and choose values for If/While style workflows',
      icon: 'riArrowLeftRightLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditLogicTools',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'leftJson', 'rightJson', 'valuesJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'compare',
        operator: 'contains',
        leftJson: '"visual coding"',
        rightJson: '"coding"',
        valuesJson: '[\n  true,\n  1,\n  "yes"\n]',
        whenTrueJson: '"yes"',
        whenFalseJson: '"no"',
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'logic_result',
      },
    },
    'variable-store': {
      name: 'Variable Store',
      description: 'Persist typed variables that AI, MCP and Automa blocks can share',
      icon: 'mdiVariable',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditVariableStore',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'variableStoreName', 'valueJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'get',
        variableStoreName: 'counter',
        variableType: 'number',
        variableScope: 'project',
        variableDescription: '',
        valueJson: '1',
        delta: 1,
        ...baseBridgeData,
        returnPath: 'result.value',
        variableName: 'stored_variable',
      },
    },
    'loop-helper': {
      name: 'Loop Helper',
      description: 'Generate range, repeated, chunked or enumerated lists for Automa Loop Data blocks',
      icon: 'riRepeat2Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditLoopHelper',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'itemsJson', 'itemJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'range',
        itemsJson: '[\n  "alpha",\n  "beta",\n  "gamma"\n]',
        itemJson: '{\n  "ok": true\n}',
        start: 0,
        end: 5,
        step: 1,
        inclusive: false,
        times: 3,
        size: 2,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'loop_items',
      },
    },
    'file-path-tools': {
      name: 'File / Path Tools',
      description: 'Read, write, list, copy and normalize sandboxed files and paths',
      icon: 'riFolderLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditFilePathTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'path', 'text', 'source', 'target', 'partsJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'write',
        path: 'demo/output.txt',
        text: 'Hello from Visual Coding',
        source: 'demo/output.txt',
        target: 'demo/copy.txt',
        partsJson: '[\n  "demo",\n  "output.txt"\n]',
        base: '.',
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'file_result',
      },
    },
    'wait-tools': {
      name: 'Wait / Retry Tools',
      description: 'Wait for time, files, HTTP responses, browser selectors and text',
      icon: 'riTimeLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditWaitTools',
      category: 'conditions',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'path', 'url', 'selector', 'text', 'actionPayloadJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'sleep',
        seconds: 1,
        path: 'demo/output.txt',
        url: 'https://example.com',
        selector: 'h1',
        text: 'Example',
        browserEngine: 'chromium',
        fileMode: 'exists',
        status: 200,
        state: 'visible',
        headless: true,
        timeoutSeconds: 10,
        interval: 0.5,
        retryAction: 'http_request',
        actionPayloadJson: '{\n  "url": "https://example.com"\n}',
        attempts: 3,
        delaySeconds: 1,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'wait_result',
      },
    },
    'profile-action': {
      name: 'Profile Action',
      description: 'Create, copy, lock, delete and attach metadata/cookies to browser profiles',
      icon: 'riUser3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditProfileAction',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'profileName', 'targetProfileName', 'metadataJson', 'cookiesJson', 'lockToken', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'create',
        profileName: 'demo-browser-profile',
        targetProfileName: 'demo-browser-profile-copy',
        browserEngine: 'chromium',
        profileDescription: '',
        metadataJson: '{\n  "notes": "Visual Coding profile"\n}',
        cookiesJson: '[]',
        lockToken: '',
        force: false,
        overwrite: false,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'profile_result',
      },
    },
    'network-recorder-import': {
      name: 'Network Recorder Import',
      description: 'Capture browser network events and generate HTTP Client workflow blocks',
      icon: 'riGlobalLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditNetworkRecorderImport',
      category: 'browser',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'url', 'html', 'profileName', 'workflowName', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        source: 'url',
        url: 'https://example.com',
        html: '<main><h1>Network Capture</h1></main>',
        browserEngine: 'chromium',
        profileName: '',
        workflowName: 'captured-http-workflow',
        limit: 12,
        headless: true,
        ...baseBridgeData,
        timeout: 60000,
        returnPath: 'result.workflow.artifact',
        variableName: 'captured_workflow',
      },
    },
    'result-tools': {
      name: 'Result / Log Tools',
      description: 'Create structured logs, message payloads and random values',
      icon: 'riInformationLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditResultTools',
      category: 'data',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'message', 'dataJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        mode: 'log',
        level: 'info',
        message: 'Visual Coding result',
        dataJson: '{\n  "ok": true\n}',
        min: 0,
        max: 100,
        integer: true,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'result_value',
      },
    },
    'http-client': {
      name: 'HTTP Client',
      description: 'Run an HTTP request through the Visual Coding bridge',
      icon: 'riEarthLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditHttpClient',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'url', 'headersJson', 'body', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        method: 'GET',
        url: 'https://example.com',
        headersJson: '{}',
        bodyMode: 'none',
        body: '',
        jsonBody: '{}',
        timeout: 20,
        maxChars: 200000,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'http_response',
      },
    },
    'library-runner': {
      name: 'Library Runner',
      description: 'Run Python or Node code with pip/npm libraries through the Visual Coding bridge',
      icon: 'riCodeSSlashLine',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditLibraryRunner',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'runtime', 'packagesJson', 'code', 'inputJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        runtime: 'python',
        packagesJson: '[]',
        code: 'result = input_data["x"] * 3',
        inputJson: '{\n  "x": 14\n}',
        executionTimeout: 30,
        installTimeout: 180,
        ...baseBridgeData,
        returnPath: 'result',
        variableName: 'library_result',
      },
    },
    'telegram-bot-builder': {
      name: 'Telegram Bot Builder',
      description: 'Generate a Python or Node Telegram bot project from an Automa workflow',
      icon: 'riChat3Line',
      component: 'BlockBasicWithFallback',
      editComponent: 'EditTelegramBotBuilder',
      category: 'general',
      inputs: 1,
      outputs: 2,
      allowedInputs: true,
      maxConnection: 1,
      refDataKeys: ['bridgeUrl', 'appName', 'tokenResource', 'startText', 'commandHandlersJson', 'variableName'],
      autocomplete: ['variableName'],
      data: {
        disableBlock: false,
        description: '',
        runtime: 'python',
        appName: 'visual-coding-telegram-bot',
        tokenResource: 'telegram_bot_token',
        startText: 'Hello from Visual Coding bot',
        commandHandlersJson: '[\n  {"command":"ping","response":"pong"}\n]',
        executionTimeout: 30,
        ...baseBridgeData,
        returnPath: 'result.dir',
        variableName: 'telegram_bot_dir',
      },
    },
  };
}
